export interface NpmMaintainer {
  username: string;
}

export interface NpmSearchPackage {
  name: string;
  maintainers?: NpmMaintainer[];
  links?: { repository?: string };
  repository?: { url?: string; type?: string };
}

export interface NpmSearchObject {
  package: NpmSearchPackage;
  downloads?: {
    weekly?: number;
    monthly?: number;
  };
}

export interface NpmSearchResponse {
  objects: NpmSearchObject[];
  total: number;
}

export interface NpmPackageRow {
  name: string;
  projectKey: string;
  projectLabel: string;
  downloads7d: number;
  downloads30d: number;
  shareOfTotal30d: number;
  /** Daily downloads aligned to `NpmPayload.daily`; absent outside the fetched top N. */
  daily?: number[];
  dataThrough?: string;
}

export interface NpmDailyPoint {
  date: string;
  downloads: number;
}

export interface NpmProjectRow {
  key: string;
  label: string;
  packageCount: number;
  downloads7d: number;
  downloads30d: number;
  shareOfTotal30d: number;
  pinned: boolean;
}

export interface NpmPayload {
  /** Generated by mock mode or the public demo. */
  mock?: boolean;
  maintainer: string;
  packageCount: number;
  totalDownloads7d: number;
  totalDownloads30d: number;
  totalNote: string;
  projects: NpmProjectRow[];
  packages: NpmPackageRow[];
  /** Summed daily downloads for the packages that have a series. */
  daily?: NpmDailyPoint[];
  /** Last day npm has processed; usually one or two days behind today. */
  dataThrough?: string | null;
  dailyCoverage?: { packages: number; shareOfTotal30d: number };
  fetchedAt: string;
  cache: {
    fresh: boolean;
    ageSeconds: number;
    stale: boolean;
    source: "live" | "cache" | "stale-cache";
  };
  partialFailure: boolean;
  warning?: string;
  errors: string[];
}
