// Client-side mirrors of the Worker payloads in ../../src/types.ts and ../../src/npm/types.ts.

export interface CacheMetadata {
  fresh: boolean;
  ageSeconds: number;
  stale: boolean;
  source: "live" | "cache" | "stale-cache";
  /** Last refresh attempt, ISO time. */
  lastAttemptAt?: string;
  /** Set when the last attempt failed; the payload is the previous good one. */
  lastError?: string | null;
}

export interface QuotaSummary {
  lowestHourlyRemaining?: number;
  lowestDailyRemaining?: number;
  lowestConcurrentRemaining?: number;
  reportingPropertyCount: number;
}

export interface PropertyResult {
  id: string;
  name: string;
  accountName: string;
  activeUsers: number;
  shareOfTotal: number;
  status: "ok" | "error";
  error?: string;
}

export interface CountryBreakdown {
  country: string;
  activeUsers: number;
  shareOfTotal: number;
}

export interface RealtimeArrival {
  city: string;
  country: string;
  property: string;
  minutesAgo: number;
  activeUsers: number;
}

export interface RealtimeEvent {
  minutesAgo: number;
  eventName: string;
  property: string;
  propertyId: string;
  count: number;
}

export interface RealtimePage {
  title: string;
  property: string;
  propertyId: string;
  activeUsers: number;
  views: number;
}

export interface RealtimePayload {
  totalActiveUsers: number;
  totalNote: string;
  properties: PropertyResult[];
  countries: CountryBreakdown[];
  arrivals?: RealtimeArrival[];
  pages?: RealtimePage[];
  events?: RealtimeEvent[];
  fetchedAt: string;
  cache: CacheMetadata;
  partialFailure: boolean;
  errors: string[];
  quotaSummary: QuotaSummary | null;
  mock: boolean;
}

export interface PortfolioDailyPoint {
  date: string;
  sessions: number;
  engagedSessions: number;
  views: number;
  keyEvents: number;
  families: Record<string, number>;
}

export interface PropertyActivitySummary {
  id: string;
  name: string;
  family: string;
  accountName: string;
  status: "ok" | "error";
  error?: string;
  lastActiveDate: string | null;
  sessionsToday: number;
  sessions7d: number;
  previousSessions7d: number;
  change7d: number | null;
  engagementRate7d: number | null;
  dailySessions: Array<{ date: string; value: number }>;
}

export interface OverviewPayload {
  fetchedAt: string;
  windowDays: number;
  totals: {
    sessions30d: number;
    previousSessions30d: number;
    sessionChange30d: number | null;
    engagedSessions30d: number;
    engagementRate30d: number | null;
    views30d: number;
    keyEvents30d: number;
  };
  daily: PortfolioDailyPoint[];
  families: string[];
  properties: PropertyActivitySummary[];
  cache: CacheMetadata;
  partialFailure: boolean;
  errors: string[];
  quotaSummary: QuotaSummary | null;
  mock: boolean;
}

export interface NpmPackageRow {
  name: string;
  projectKey: string;
  projectLabel: string;
  downloads7d: number;
  downloads30d: number;
  shareOfTotal30d: number;
  daily?: number[];
  dataThrough?: string;
}

export interface NpmDailyPoint {
  date: string;
  downloads: number;
}

export interface NpmProjectRow {
  key: string;
  label: string;
  packageCount: number;
  downloads7d: number;
  downloads30d: number;
  shareOfTotal30d: number;
  pinned: boolean;
}

export interface NpmPayload {
  /** Generated by mock mode or the public demo. */
  mock?: boolean;
  maintainer: string;
  packageCount: number;
  totalDownloads7d: number;
  totalDownloads30d: number;
  totalNote: string;
  projects: NpmProjectRow[];
  packages: NpmPackageRow[];
  daily?: NpmDailyPoint[];
  dataThrough?: string | null;
  dailyCoverage?: { packages: number; shareOfTotal30d: number };
  fetchedAt: string;
  cache: CacheMetadata;
  partialFailure: boolean;
  warning?: string;
  errors: string[];
}

export interface SearchQueryRow {
  query: string;
  site: string;
  clicks: number;
  impressions: number;
  ctr: number;
  position: number;
}

export interface SearchDailyPoint {
  date: string;
  clicks: number;
  impressions: number;
}

export interface SearchSiteSummary {
  propertyId: string;
  name: string;
  domain: string;
  siteUrl: string | null;
  status: "ok" | "unshared" | "error";
  clicks: number;
  impressions: number;
  ctr: number | null;
  position: number | null;
  previousClicks: number;
  daily: SearchDailyPoint[];
  topQueries: SearchQueryRow[];
}

export type SearchSetup = "api-disabled" | "no-access";

export interface SearchPayload {
  fetchedAt: string;
  windowDays: number;
  totals: {
    clicks: number;
    previousClicks: number;
    clickChange: number | null;
    impressions: number;
    ctr: number | null;
    position: number | null;
  };
  daily: SearchDailyPoint[];
  sites: SearchSiteSummary[];
  topQueries: SearchQueryRow[];
  cache: CacheMetadata;
  partialFailure: boolean;
  errors: string[];
  mock: boolean;
  /** Present when Search Console is not connected yet. */
  setup?: SearchSetup;
}
